### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by caophuoclong1** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#1]
Hi guy, thank to your efi hackintosh but i have a problem with this. My computer the same to you but when i use your efi then i recive a erorr here https://imgur.com/BaGtRaH . Sorry my English is too bad. I'm forward to replying from you

**Comment by z3r0c00l-2k** [comment]
Where did you get the installer for mac?

**Comment by caophuoclong1** [comment]
I find a installer big sur from group vno hackintosh in fb and it works for everyone. Could you give me your installer? Thanks!

**Comment by z3r0c00l-2k** [comment]
https://dortania.github.io/OpenCore-Install-Guide/
follow this guide

**Comment by z3r0c00l-2k** [comment]
you can download mac images from [here](https://www.olarila.com/topic/6278-new-vanilla-olarila-images/), burn it using  [etcher](https://www.balena.io/etcher/),

**Comment by caophuoclong1** [comment]
oh thank you so much, i found an error. My ssd Micron 2200 has been not supported by apple so i can boot it in.

**Comment by z3r0c00l-2k** [comment]
So then i am closing this issue.
