### ISSUE TITLE
The touchpad still doesn't work can you please fix it....

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#11]
All is working fine except the touchpad... :( It annoys me just so baaaddddd @z3r0c00l-2k

**Comment by z3r0c00l-2k** [comment]
@VaibhavKukreti-Kathud read these docs and try to fix it yourself [](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad.html).
I kinda busy with my work.

**Comment by VaibhavKukreti-Kathud** [comment]
can you please link me to the docs you are referring to?

**Comment by VaibhavKukreti-Kathud** [comment]
And also @z3r0c00l-2k does the type-c port work?

**Comment by z3r0c00l-2k** [comment]
@VaibhavKukreti-Kathud yes, ut does
