### ISSUE TITLE
For the bluetooth help

### ISSUE THREAD

**Issue by VampFOX67** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#2]
I have the same Acer Nitro 5 with lower spec, processor intel i5 9300h and gtx1050 and all other specs are same.

see the issue with bluetooth not working is SSDT-GPIO because this one also bugged my bluetooth when in use, and as I changed to SSDT-XOSI , bluetooth came online.

**Comment by z3r0c00l-2k** [comment]
Ohh. Thanks mate..👍 👍 👍 
I knew its related usb mapping, but i haven't got time mess around with it.
I will check this.

**Comment by z3r0c00l-2k** [comment]
Bro bro can u ping me on telegram?
https://t.me/z3r0c00l_2k
