### ISSUE TITLE
Trackpad not works when mouse is connected

### ISSUE THREAD

**Issue by kalilmaciel** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#4]
Hi

I´m having a problem with the trackpad. My notebook is using Big Sur and Windows 10 in dual boot. When i'm using Windows,  The trackpad works like a charm. But when using Big Sur, the trackpad is not detected. I already tryed press Fn + F7 but nothing happens. I remember that in previous version of your EFI the trackpad used to work.

What can I do trackpad back to work?

Thanks

**Comment by z3r0c00l-2k** [comment]
@kalilmaciel what is your notebook's model number?

**Comment by kalilmaciel** [comment]
Hi

My Notebook is a Acer Nitro 5 model  AN515-54.

I'm using your EFI and everything works like a charm. The trackpad is the only thing that is not working now.

**Comment by kalilmaciel** [comment]
Hi

I don't know if there's something about this but yesterday was launched a new version of bios for my laptop. After upgrade it the trackpad is now working perfectly.

Thanks for everyone.
