### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by As1Wills** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#6]
I don't know how to install
pls help

**Comment by z3r0c00l-2k** [comment]
i have added installation steps in the readme

**Comment by As1Wills** [comment]
Thanks

**Comment by As1Wills** [comment]
The read me is useless there is nothing

**Comment by z3r0c00l-2k** [comment]
what do mean nothing?

**Comment by z3r0c00l-2k** [comment]
if you are looking for detailed steps, follow this link 
https://dortania.github.io/OpenCore-Install-Guide/
