### ISSUE TITLE
Wifi is not active

### ISSUE THREAD

**Issue by kalilmaciel** [z3r0c00l-2k/Nitro-5-Hackintosh-OC#7]
Hi.

After I upgraded to this new version, I can't get wifi enabled. When I open the network connections window, a <<Location.string>> message appears for a brief moment and then goes out. I believe the wifi file is not working.

**Comment by z3r0c00l-2k** [comment]
Which mac version are you using?

**Comment by z3r0c00l-2k** [comment]
This repo currently contains the wifi driver for Monterey. 
Btw I downgraded to Bigsur because of random crashes and poor performance

**Comment by kalilmaciel** [comment]
Hi
I'm still using the Big Sur 11.5.2

I will wait the final version of Monterrey be launched to upgrade.
The last version is working like a charm.

Thanks for your work.

**Comment by z3r0c00l-2k** [comment]
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0
from here download AirportItlwm.kext for bigsur and replace it in `EFI/OC/Kexts`
